substitutions:
  _REGION: asia-south1
  _REPO: gcp-devops-demo
  _CLUSTER: devops-demo-cluster
  _IMAGE: asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-devops-demo/demo-app

steps:

  - name: "gcr.io/cloud-builders/docker"
    id: "build-image"
    args:
      - build
      - -t
      - "asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-devops-demo/demo-app:$SHORT\
        _SHA"
      - -t
      - "asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-devops-demo/demo-app:latest"
      - ./app

  - name: "gcr.io/cloud-builders/docker"
    id: "push-image"
    args:
      - push
      - --all-tags
      - "asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-devops-demo/demo-app"

  - name: "gcr.io/cloud-builders/gcloud"
    id: "get-credentials"
    args:
      - container
      - clusters
      - get-credentials
      - devops-demo-cluster
      - --zone=asia-south1-a
      - --project=$PROJECT_ID

  - name: "gcr.io/cloud-builders/kubectl"
    id: "apply-configmap"
    args: [ "apply", "-f", "k8s/configmap.yaml" ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-south1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=devops-demo-cluster"

  - name: "gcr.io/cloud-builders/kubectl"
    id: "update-image"
    args:
      - set
      - image
      - deployment/demo-app
      - demo-app=asia-south1-docker.pkg.dev/$PROJECT_ID/gcp-devops-demo/demo-app:$SHORT_SHA
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-south1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=devops-demo-cluster"

  - name: "gcr.io/cloud-builders/kubectl"
    id: "verify-rollout"
    args:
      - rollout
      - status
      - deployment/demo-app
      - --timeout=120s
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-south1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=devops-demo-cluster"

options:
  logging: CLOUD_LOGGING_ONLY
