steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/polygon-infra/devops-demo-repo/color-app:$SHORT_SHA'
      - '-t'
      - 'asia-south1-docker.pkg.dev/polygon-infra/devops-demo-repo/color-app:latest'
      - './app'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args: ['push', '--all-tags', 'asia-south1-docker.pkg.dev/polygon-infra/devops-demo-repo/color-app']
    waitFor: ['build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'update-gitops'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://Brahathees:$$GITHUB_TOKEN@github.com/Venu890/gcp-devops-gitops.git /workspace/gitops
        cd /workspace/gitops
        sed -i "s|image:.*color-app:.*|        image: asia-south1-docker.pkg.dev/polygon-infra/devops-demo-repo/color-app:$SHORT_SHA|g" envs/dev/rollout.yaml
        sed -i "s|  tag:.*|  tag: \"$SHORT_SHA\"|g" envs/dev/values.yaml
        git config user.email "cloudbuild@polygon-infra.com"
        git config user.name "Cloud Build"
        git add .
        git commit -m "ci: update image to $SHORT_SHA"
        git push
    waitFor: ['push']
    secretEnv: ['GITHUB_TOKEN']

availableSecrets:
  secretManager:
  - versionName: projects/polygon-infra/secrets/github-token/versions/latest
    env: 'GITHUB_TOKEN'

images:
  - 'asia-south1-docker.pkg.dev/polygon-infra/devops-demo-repo/color-app:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
